baseURL = 'https://lb2kk.no/'
languageCode = 'en-us'
title = "LB2KK"
theme = "hugo-theme-m10c"

[params]
author = "Per Thomas Jahr"
description = "Join me on my journey into the world of amateur radio and electronics. As a newly licensed operator, I document my projects, experiments, and discoveries â€” mostly for myself, but with the hope that you might find something useful along the way."
avatar = "logo.webp"

 [params.header]

  [[params.social]]
    icon = "brand-github"
    name = "Github"
    url = "https://github.com/perja12"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2


[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      wrapStandAloneImageWithinParagraph = false
      [markup.goldmark.parser.attribute]
        block = true
        title = true


